In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [3]:
import pandas as pd

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 1, 0, 0, 0, 1, 1]
})

df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            1
11           0.27             33              11            0
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [21]:
X=df[['soil_moisture','temperature_c','sunlight_hours']]
y=df['needs_water']

In [22]:
X_min=X.min()
X_max=X.max()
X_scaled=(X-X_min)/(X_max-X_min+1e-8)

In [23]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
...     X_scaled, y, test_size=0.25, random_state=42)

In [38]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [42]:
model.compile(optimizer='sgd',loss='binary_cross_entropy',metrics=['accuracy'])

In [45]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.6634 - val_accuracy: 0.2500 - val_loss: 0.7210
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6625 - val_accuracy: 0.2500 - val_loss: 0.7209
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6624 - val_accuracy: 0.2500 - val_loss: 0.7208
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6627 - val_accuracy: 0.2500 - val_loss: 0.7207
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6627 - val_accuracy: 0.2500 - val_loss: 0.7206
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6623 - val_accuracy: 0.2500 - val_loss: 0.7204
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6625 - val_accuracy: 0.2500 - val_loss: 0.7204
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6632 - val_accuracy: 0.2500 - val_loss: 0.7202
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6617 - val_accuracy: 0.2500 - val_loss: 0.7201
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6614 - val_accuracy: 0.2500 - val_loss: 0.7200
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6619 - val_accuracy: 0.2500 - val_loss: 0.7198
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6612 - val_accuracy: 0.2500 - val_loss: 0.7197
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6611 - val_accuracy: 0.2500 - val_loss: 0.7196
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6612 - val_accuracy: 0.2500 - val_loss: 0.7195
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6609 - val_accuracy: 0.2500 - val_loss: 0.7194
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6610 - val_accuracy: 0.2500 - val_loss: 0.7192
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6612 - val_accuracy: 0.2500 - val_loss: 0.7190
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6605 - val_accuracy: 0.2500 - val_loss: 0.7189
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6604 - val_accuracy: 0.2500 - val_loss: 0.7188
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6603 - val_accuracy: 0.2500 - val_loss: 0.7186
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6604 - val_accuracy: 0.2500 - val_loss: 0.7185
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6607 - val_accuracy: 0.2500 - val_loss: 0.7184
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6601 - val_accuracy: 0.2500 - val_loss: 0.7183
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6599 - val_accuracy: 0.2500 - val_loss: 0.7182
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6604 - val_accuracy: 0.2500 - val_loss: 0.7181
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6603 - val_accuracy: 0.2500 - val_loss: 0.7180
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6597 - val_accuracy: 0.2500 - val_loss: 0.7179
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6603 - val_accuracy: 0.2500 - val_loss: 0.7179
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6598 - val_accuracy: 0.2500 - val_loss: 0.7178
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6600 - val_accuracy: 0.2500 - val_loss: 0.7176
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6594 - val_accuracy: 0.2500 - val_loss: 0.7175
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6591 - val_accuracy: 0.2500 - val_loss: 0.7175
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6590 - val_accuracy: 0.2500 - val_loss: 0.7174
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6591 - val_accuracy: 0.2500 - val_loss: 0.7173
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6590 - val_accuracy: 0.2500 - val_loss: 0.7172
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6587 - val_accuracy: 0.2500 - val_loss: 0.7171
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6587 - val_accuracy: 0.2500 - val_loss: 0.7170
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6601 - val_accuracy: 0.2500 - val_loss: 0.7169
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6586 - val_accuracy: 0.2500 - val_loss: 0.7169
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6586 - val_accuracy: 0.2500 - val_loss: 0.7168
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6585 - val_accuracy: 0.2500 - val_loss: 0.7167
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6582 - val_accuracy: 0.2500 - val_loss: 0.7166
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6584 - val_accuracy: 0.2500 - val_loss: 0.7165
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6581 - val_accuracy: 0.2500 - val_loss: 0.7163
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6586 - val_accuracy: 0.2500 - val_loss: 0.7162
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6578 - val_accuracy: 0.2500 - val_loss: 0.7160
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6578 - val_accuracy: 0.2500 - val_loss: 0.7158
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6576 - val_accuracy: 0.2500 - val_loss: 0.7157
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6577 - val_accuracy: 0.2500 - val_loss: 0.7155
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6590 - val_accuracy: 0.2500 - val_loss: 0.7153
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6578 - val_accuracy: 0.2500 - val_loss: 0.7152
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6572 - val_accuracy: 0.2500 - val_loss: 0.7150
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6579 - val_accuracy: 0.2500 - val_loss: 0.7149
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6577 - val_accuracy: 0.2500 - val_loss: 0.7147
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6573 - val_accuracy: 0.2500 - val_loss: 0.7145
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6568 - val_accuracy: 0.2500 - val_loss: 0.7144
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6566 - val_accuracy: 0.2500 - val_loss: 0.7142
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6576 - val_accuracy: 0.2500 - val_loss: 0.7141
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6563 - val_accuracy: 0.2500 - val_loss: 0.7139
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6562 - val_accuracy: 0.2500 - val_loss: 0.7137
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6562 - val_accuracy: 0.2500 - val_loss: 0.7137
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6560 - val_accuracy: 0.2500 - val_loss: 0.7138
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6560 - val_accuracy: 0.2500 - val_loss: 0.7138
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6566 - val_accuracy: 0.2500 - val_loss: 0.7136
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6557 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6561 - val_accuracy: 0.2500 - val_loss: 0.7135
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6555 - val_accuracy: 0.2500 - val_loss: 0.7135
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6562 - val_accuracy: 0.2500 - val_loss: 0.7133
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6558 - val_accuracy: 0.2500 - val_loss: 0.7133
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6552 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6560 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6553 - val_accuracy: 0.2500 - val_loss: 0.7134
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6554 - val_accuracy: 0.2500 - val_loss: 0.7132
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6547 - val_accuracy: 0.2500 - val_loss: 0.7132
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6553 - val_accuracy: 0.2500 - val_loss: 0.7133
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6546 - val_accuracy: 0.2500 - val_loss: 0.7130
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6546 - val_accuracy: 0.2500 - val_loss: 0.7130
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6546 - val_accuracy: 0.2500 - val_loss: 0.7128
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6542 - val_accuracy: 0.2500 - val_loss: 0.7128
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6557 - val_accuracy: 0.2500 - val_loss: 0.7128
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6547 - val_accuracy: 0.2500 - val_loss: 0.7126
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6537 - val_accuracy: 0.2500 - val_loss: 0.7125
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6542 - val_accuracy: 0.2500 - val_loss: 0.7125
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6536 - val_accuracy: 0.2500 - val_loss: 0.7126
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6536 - val_accuracy: 0.2500 - val_loss: 0.7126
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6532 - val_accuracy: 0.2500 - val_loss: 0.7126
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6535 - val_accuracy: 0.2500 - val_loss: 0.7123
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.6530 - val_accuracy: 0.2500 - val_loss: 0.7123
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6534 - val_accuracy: 0.2500 - val_loss: 0.7123
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6528 - val_accuracy: 0.2500 - val_loss: 0.7121
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6526 - val_accuracy: 0.2500 - val_loss: 0.7120
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6528 - val_accuracy: 0.2500 - val_loss: 0.7120
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6528 - val_accuracy: 0.2500 - val_loss: 0.7120
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6528 - val_accuracy: 0.2500 - val_loss: 0.7120
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.6521 - val_accuracy: 0.2500 - val_loss: 0.7116
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6522 - val_accuracy: 0.2500 - val_loss: 0.7114
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.6524 - val_accuracy: 0.2500 - val_loss: 0.7111
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5833 - loss: 0.6532 - val_accuracy: 0.2500 - val_loss: 0.7109
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5833 - loss: 0.6524 - val_accuracy: 0.2500 - val_loss: 0.7109
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.6518 - val_accuracy: 0.2500 - val_loss: 0.7109